### ISSUE TITLE
Skype and Office 2016 sometimes crashes when language is changed.

### ISSUE THREAD

**Issue by xcariba** [gooli/recaps#3]
Sometimes when i change language in Microsoft Word 2016 it freezes and crashes. Skype is a lot worse, freezes almost every time.

**Comment by finereli** [comment]
I've heard from multiple sources of this issue but unfortunately I don't have the resources to figure out why this is happening. I use OSX exclusively these days.

You can use AutoHot key script from https://autohotkey.com/board/topic/65264-capslock-to-change-input-language/ to switch languages with Capslock instead of Recaps.

I'm sorry I can't be of any further assistance.
